project_id = "wgeelknadpxnmeomuenc"

[functions.check-password-breach]
verify_jwt = false

[functions.validate-password-strength]
verify_jwt = false

[functions.track-email]
verify_jwt = false

[functions.monitor-email-engagement]
verify_jwt = false
